### ISSUE TITLE
exec js crashes nodejs on second attempt

### ISSUE THREAD

**Issue by wayneseymour** [winsonwq/webdriver-helper#8]
Hello there, I'm trying to exec arbitrary funcs for my purposes.
To get started I followed your [docs](https://github.com/winsonwq/webdriver-helper/tree/add_execute_js#browserexecscript-args-callback) and when I tried to exec that func more than once, node crashes back to the shell.

**Note: This was in the node repl.**

**Comment by wayneseymour** [comment]
Error: 

``` sh
> browser.exec('alert("hello world!");', function() {
...   browser.dialog().text(function (text) {
.....
.....   });
... });
{ then: [Function: then],
  cancel: [Function: cancel],
  isPending: [Function: isPending] }
>
/Users/wayne/Documents/dev/repos/merlin.js/node_modules/selenium-webdriver/lib/webdriver/promise.js:1702
      throw error;
            ^
UnknownError: '[JavaScript Error: "a is null" {file: "file:///var/folders/5l/bmrx9fm93_x__j020gmq7tmr0000gn/T/anonymous8234822359118271143webdriver-profile/extensions/fxdriver@googlecode.com/components/command_processor.js" line: 8120}]' when calling method: [nsICommandProcessor::execute]
Build info: version: '2.39.0', revision: 'ff23eac', time: '2013-12-16 16:11:15'
System info: host: 'Waynes-MacBook-Pro.local', ip: '10.84.124.10', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.9.1', java.version: '1.8.0-ea'
Driver info: driver.version: unknown
    at new bot.Error (/Users/wayne/Documents/dev/repos/merlin.js/node_modules/selenium-webdriver/lib/atoms/error.js:109:18)
    at Object.bot.response.checkResponse (/Users/wayne/Documents/dev/repos/merlin.js/node_modules/selenium-webdriver/lib/atoms/response.js:106:9)
    at /Users/wayne/Documents/dev/repos/merlin.js/node_modules/selenium-webdriver/lib/webdriver/webdriver.js:276:20
```
